services:
  - type: web
    name: sunraku-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_CHAT_ID
        sync: false
